# Generated by Django 4.0.2 on 2022-08-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ci',
            field=models.CharField(default=1, max_length=150, verbose_name='ci'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default=1, max_length=20, verbose_name='nombre'),
            preserve_default=False,
        ),
    ]
