# Generated by Django 4.0.2 on 2022-08-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_empleado_ci_empleado_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
    ]
