# Generated by Django 4.0.2 on 2022-09-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('price', models.FloatField(max_length=150, unique=True, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
