# Generated by Django 4.0.2 on 2022-09-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_producto_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Talla'),
            preserve_default=False,
        ),
    ]
