# Generated by Django 4.0.2 on 2022-10-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_producto_color_producto_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=150, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.FloatField(max_length=150, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(max_length=150, verbose_name='Talla'),
        ),
    ]
