# Generated by Django 4.0.2 on 2022-10-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_producto_color_alter_producto_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=150, verbose_name='correo')),
                ('telefono', models.CharField(max_length=150, verbose_name='telefono')),
                ('cedula', models.IntegerField(max_length=150, verbose_name='cedula')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
