# Generated by Django 4.0.2 on 2022-11-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(verbose_name='cedula'),
        ),
    ]
