# Generated by Django 4.1.4 on 2022-12-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.categoria', verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name_cat',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre_cat'),
        ),
    ]
