# Generated by Django 4.1.4 on 2022-12-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.color', verbose_name='color'),
        ),
    ]
