# Generated by Django 4.1.4 on 2022-12-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_producto_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='cantidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='product/%Y/%m/%d', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
