# Generated by Django 4.1.4 on 2022-12-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_rename_color_colores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
