# Generated by Django 4.1.4 on 2022-12-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_alter_producto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
    ]
