# Generated by Django 4.1.4 on 2022-12-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_remove_categoria_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo_cat',
            field=models.CharField(max_length=150, null=True, verbose_name='Tipo_cat'),
        ),
    ]
