# Generated by Django 4.1.4 on 2022-12-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_categoria_tipo_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='name_cat',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_cat',
            field=models.CharField(max_length=150, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta'),
        ),
    ]
