# Generated by Django 4.1.4 on 2022-12-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_genero_talla_alter_categoria_name_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='gen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.genero', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name_cat',
            field=models.CharField(max_length=150, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(max_length=150, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.talla', verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='talla',
            name='Talla',
            field=models.CharField(max_length=150, verbose_name='Talla'),
        ),
    ]
