# Generated by Django 4.1.4 on 2023-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_rename_talla_talla_talla_remove_producto_gen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre_proveedor')),
                ('ruc', models.CharField(max_length=150, verbose_name='ruc_proveedor')),
                ('telefono', models.IntegerField(verbose_name='telefono_proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
    ]
