# Generated by Django 4.1.4 on 2023-01-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_buy_detbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='price_buy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de compra'),
        ),
    ]
