# Generated by Django 4.1.4 on 2023-01-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_producto_price_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empleado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=1, max_length=150, verbose_name='direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(default=1, max_length=150, verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='ruc',
            field=models.CharField(max_length=150, verbose_name='Ruc'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
