# Generated by Django 4.1.4 on 2023-01-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_delete_empleado_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='comprobante',
            field=models.IntegerField(default=0),
        ),
    ]
