# Generated by Django 4.1.4 on 2023-01-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_alter_creditsale_price_alter_sale_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
    ]
