# Generated by Django 4.1.4 on 2023-01-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_creditsale_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='auditoria',
            fields=[
                ('codigo_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=1)),
                ('datos_viejos', models.CharField(max_length=5000, null=True)),
                ('datos_nuevos', models.CharField(max_length=5000, null=True)),
                ('usuario', models.CharField(max_length=45)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detbuy',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detbuy',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='detbuy',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detbuy',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detsale',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detsale',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='detsale',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detsale',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
