# Generated by Django 4.1.4 on 2023-01-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_auditoria_buy_date_create_buy_date_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='codigo_auditoria',
            new_name='cod_auditoria',
        ),
    ]
