# Generated by Django 4.1.4 on 2023-01-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_rename_codigo_auditoria_auditoria_cod_auditoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='cod_auditoria',
            new_name='codigo_auditoria',
        ),
    ]
