# Generated by Django 4.1.4 on 2023-01-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_rename_cod_auditoria_auditoria_codigo_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='datos_nuevos',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='datos_viejos',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
