# Generated by Django 4.1.4 on 2023-01-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_alter_auditoria_datos_nuevos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='datos_nuevos',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='datos_viejos',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
